export const GESS_BLOQUE_IDS = [
  "EXT-IZQ-01","EXT-IZQ-02","EXT-IZQ-03","EXT-IZQ-04","EXT-IZQ-05","EXT-IZQ-06",
  "EXT-IZQ-07","EXT-IZQ-08","EXT-IZQ-09","EXT-IZQ-10",
  "EXT-DER-01","EXT-DER-02","EXT-DER-03","EXT-DER-04","EXT-DER-05","EXT-DER-06",
  "EXT-DER-07","EXT-DER-08","EXT-DER-09","EXT-DER-10",
  "INT-IZQ-A1","INT-IZQ-A2","INT-IZQ-A3","INT-IZQ-A4","INT-IZQ-A5","INT-IZQ-A6","INT-IZQ-A7","INT-IZQ-A8",
  "INT-IZQ-B1","INT-IZQ-B2","INT-IZQ-B3","INT-IZQ-B4","INT-IZQ-B5","INT-IZQ-B6","INT-IZQ-B7","INT-IZQ-B8",
  "INT-DER-1","INT-DER-2","INT-DER-3","INT-DER-4","INT-DER-5","INT-DER-6","INT-DER-7","INT-DER-8",
  "ISLA-GRANDE-1","ISLA-GRANDE-2","ISLA-GRANDE-3","ISLA-GRANDE-4",
] as const;

export type GessBloqueId = (typeof GESS_BLOQUE_IDS)[number];
